# Generated by Django 5.2.7 on 2025-11-07 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=522, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=50)),
                ('bill_to', models.CharField(max_length=200)),
                ('site_location', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('remittance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='static/invoices/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('pcs', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='webapp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesPaymentsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='static/invoices_payments_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status_title', models.CharField(default='Pending', max_length=522)),
                ('is_approved', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_paid_payment_proof', to='webapp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='MillOwnersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=522)),
                ('company', models.CharField(max_length=522)),
                ('owner_p', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mills_owners_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('units', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mills_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mills_Authorized_Point_of_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=522)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mills_units_authority', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mills_Senior_Point_of_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=522)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mills_units_senior', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mills_Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=522)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ntn', models.PositiveIntegerField(null=True)),
                ('gst', models.PositiveIntegerField(null=True)),
                ('spindles_installed', models.PositiveIntegerField(null=True)),
                ('rotors_installed', models.PositiveIntegerField(null=True)),
                ('doubling_machines_installed', models.PositiveIntegerField(null=True)),
                ('authorized_p_contact', models.CharField(max_length=522, null=True)),
                ('authorized_p_email', models.CharField(max_length=522, null=True)),
                ('senior_p_contact', models.CharField(max_length=522, null=True)),
                ('senior_p_email', models.CharField(max_length=522, null=True)),
                ('mill', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mills_units', to='webapp.mills')),
                ('mill_unit_inspectors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mill_unit_inspectors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='mill_unit_invoices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mill_unit_invoices', to='webapp.mills_units'),
        ),
        migrations.CreateModel(
            name='Inspection_Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_camera_installed', models.PositiveIntegerField(null=True)),
                ('cameras_online', models.PositiveIntegerField(null=True)),
                ('cameras_offline', models.PositiveIntegerField(null=True)),
                ('cpu_online', models.PositiveIntegerField(null=True)),
                ('cpu_offline', models.PositiveIntegerField(null=True)),
                ('gpu_online', models.PositiveIntegerField(null=True)),
                ('gpu_offline', models.PositiveIntegerField(null=True)),
                ('tnt_software_online', models.PositiveIntegerField(null=True)),
                ('tnt_software_offline', models.PositiveIntegerField(null=True)),
                ('payment_recieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('mill', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mills_inspection_reports', to='webapp.mills')),
                ('mill_unit', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mill_unit_inspection_reports', to='webapp.mills_units')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban_number', models.CharField(max_length=522, null=True)),
                ('account_title', models.CharField(max_length=522, null=True)),
                ('bank_name', models.CharField(max_length=522, null=True)),
                ('added_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts_added_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='static/payments_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('unpaid_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status_title', models.CharField(max_length=522, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by_inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records_approved_by_inspector', to='webapp.mills_authorized_point_of_contact')),
                ('mill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records_paid_by_mills', to='webapp.mills')),
                ('paid_to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records_paid_to_account', to='webapp.paymentaccounts')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records_paid_by_unit', to='webapp.mills_units')),
            ],
        ),
        migrations.CreateModel(
            name='UsersLoginLogoutActivitiesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_login_logout_activities_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
