# Generated by Django 5.2.7 on 2025-11-07 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_settings',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='static/master/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
