# Generated by Django 5.2.7 on 2025-11-07 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_master_settings_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_settings',
            old_name='attachment',
            new_name='obsidian_logo',
        ),
        migrations.AddField(
            model_name='inspection_reports',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='millownersprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'NTN must be alphanumeric (letters, numbers, or dashes).')]),
        ),
        migrations.AddField(
            model_name='mills_units',
            name='unit_id',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'NTN must be alphanumeric (letters, numbers, or dashes).')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'NTN must be alphanumeric (letters, numbers, or dashes).')]),
        ),
        migrations.AlterField(
            model_name='mills_units',
            name='ntn',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'NTN must be alphanumeric (letters, numbers, or dashes).')]),
        ),
    ]
