# Generated by Django 5.2.7 on 2025-11-07 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_attachment_master_settings_obsidian_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_settings',
            name='notf_1',
            field=models.FileField(blank=True, null=True, upload_to='static/master/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='master_settings',
            name='notf_2',
            field=models.FileField(blank=True, null=True, upload_to='static/master/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='master_settings',
            name='notf_3',
            field=models.FileField(blank=True, null=True, upload_to='static/master/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
