# Generated by Django 4.2.21 on 2025-11-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mills_units',
            name='ntn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
