# Generated by Django 5.2.7 on 2025-11-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_invoice_remittance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mills_units',
            name='cameras_installation_completed',
            field=models.BooleanField(default=False),
        ),
    ]
